#!/usr/bin/env bash

# Default to showing all files in Finder
defaults write com.apple.Finder AppleShowAllFiles 1

# Permanently hide the dock
defaults write com.apple.dock autohide-delay -float 9999; killall Dock

# Show path bar in Finder
defaults write com.apple.finder ShowPathbar -bool true

# Do not show warning when changing the file extension
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

# Set search scope to current folder
defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"

# Save screenshots in PNG format (other options: BMP, GIF, JPG, PDF, TIFF)
defaults write com.apple.screencapture type -string "png"

# Set Desktop as the default location for new Finder windows
# For other paths, use `PfLo` and `file:///full/path/here/`
defaults write com.apple.finder NewWindowTarget -string "PfHm"
defaults write com.apple.finder NewWindowTargetPath -string "file:///${HOME}/"

# Enable the Develop menu and the Web Inspector in Safari
defaults write com.apple.Safari IncludeDevelopMenu -bool true
defaults write com.apple.Safari WebKitDeveloperExtrasEnabledPreferenceKey -bool true
defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled -bool t

# Disable startup sound
sudo nvram SystemAudioVolume=%01

# Show file extensions in Finder
defaults write NSGlobalDomain "AppleShowAllExtensions" -bool "true"

# Default to list view in Finder windows
defaults write com.apple.finder "FXPreferredViewStyle" -string "Nlsv"

# Keep folders on top in Finder windows
defaults write com.apple.finder "_FXSortFoldersFirst" -bool "true"

# Automatically clear items from the trash after 30 days
defaults write com.apple.finder "FXRemoveOldTrashItems" -bool "true"

# When saving a new document start in the Home directory
defaults write NSGlobalDomain "NSDocumentSaveNewDocumentsToCloud" -bool "false"

# fonts=(
# 	font-fira-code
# )

# install_fonts() {
# 	info "Installing fonts..."
# 	brew tap homebrew/cask-fonts
# 	install_brew_casks "${fonts[@]}"
# }

# apps=(
# 	docker
# 	firefox
# 	google-chrome
# 	slack
# 	visual-studio-code
# )

# # mas_apps=(
# # 	"1444383602" # Good Notes 5
# # )

# install_macos_apps() {
# 	info "Installing macOS apps..."
# 	install_brew_casks "${apps[@]}"
# }

# # install_masApps() {
# # 	info "Installing App Store apps..."
# # 	for app in "${mas_apps[@]}"; do
# # 		mas install "$app"
# # 	done
# # }
