#!/usr/bin/env ash

OSUSERNAME=me

# This is only needed if using the default ish file system
function configure_alpine_repos () {
  rm /ish -rf
  echo https://dl-cdn.alpinelinux.org/alpine/v3.14/main > /etc/apk/repositories
  echo https://dl-cdn.alpinelinux.org/alpine/v3.14/community >> /etc/apk/repositories
  apk upgrade && apk fix
}


function set_hostname () {
  echo iphone > /etc/hostname
}

function install_essentials () {
  apk add bash
  apk add curl
  apk add sudo
  apk add openssh
  apk add git
  apk add python3
  apk add gcompat
  apk add gcc
  apk add make
  apk add libc-dev
}


function setup_ssh () {
  ssh-keygen -A
  /usr/sbin/sshd
  sed -i '/^'"PermitRootLogin"'/d' /etc/ssh/sshd_config
  echo "PermitRootLogin no" >> /etc/ssh/sshd_config
}

function build_user_directory () {
  mkdir -p /home/$OSUSERNAME/.ssh
  mkdir -p /home/$OSUSERNAME/.cache
}

function create_user () {
  adduser -D $OSUSERNAME
  passwd -d $OSUSERNAME
}

function remove_sudo_password_requirement () {
  echo "$OSUSERNAME ALL=(ALL:ALL) NOPASSWD: ALL" | tee /etc/sudoers.d/$OSUSERNAME
}

function set_user_permissions () {
  chown -R $OSUSERNAME:$OSUSERNAME /home/$OSUSERNAME/
  chown -R $OSUSERNAME:$OSUSERNAME /home/$OSUSERNAME
  chmod 700 /home/$OSUSERNAME/.ssh
  chmod 700 /home/$OSUSERNAME/.cache
}

function install_self () {
  cd /home/$OSUSERNAME
  su -s /bin/bash -c "git init && git remote add origin https://github.com/addisonbeck/dotfiles.git && git fetch && git checkout -f main && git remote set-url origin git@github.com:addisonbeck/dotfiles.git" -l $OSUSERNAME
}

function login () {
  su -l $OSUSERNAME
}

configure_alpine_repos
set_hostname
install_essentials
setup_ssh
build_user_directory
create_user
remove_sudo_password_requirement
set_user_permissions
install_self
login

# FOR LATER - To leave on in the background
# START
#cat /dev/location > /dev/null &
# STOP
#killall -9 cat
