#!/usr/bin/env bash
#
source platform

clone-fonts
install_package noto-fonts
install_package noto-fonts-emoji
install_package noto-fonts-cjk

clone-wallpaper

install-xserver
install-nomachine

install-i3
install-rofi
install_package picom
install_package rofi
install_package feh
install_package polybar

install_package neofetch
install-kitty
install_package chromium
install-gnome-keyring
