#!/usr/bin/env bash

source platform

clone_self () {
  cd $HOME 
  git init
  git remote add origin https://github.com/addisonbeck/dotfiles.git
  git fetch
  git checkout -f main 
  git remote set-url origin git@github.com:addisonbeck/dotfiles.git
}

clone_self

