#!/usr/bin/env bash

PLATFORM="unknown"
if command -v apt; then
   PLATFORM='ubuntu'
fi
if command -v brew; then
   PLATFORM='mac'
fi
if [ "$(grep -c Raspbian /etc/os-release)" -ge 1 ]; then
   PLATFORM='raspbian'
fi
if command -v pacman
then
   PLATFORM='arch'
fi
if command -v apk
then
   PACKAGEMANAGER='apk'
fi

install_package () {
  if [[ "$PLATFORM" == "ubuntu" ]]; then
    sudo apt-get -qq -o "DPkg::Lock::Timeout=180" install $1
  fi
  if [[ "$PLATFORM" == "raspbian" ]]; then
    sudo apt-get -qq -o "DPkg::Lock::Timeout=180" install $1
  fi
  if [[ "$PLATFORM" == "mac" ]]; then
    brew install -q $1 
  fi
  if [[ "$PLATFORM" == "arch" ]]; then
    sudo pacman -Syu --noconfirm $1
  fi
  if [[ "$PACKAGEMANAGER" == "apk" ]]; then
    apk add -u $1
  fi
}

remove_package () {
  if [[ "$PLATFORM" == "ubuntu" ]]; then
    sudo apt-get -qq -o "DPkg::Lock::Timeout=180" remove $1
  fi
  if [[ "$PLATFORM" == "raspbian" ]]; then
    sudo apt-get -qq -o "DPkg::Lock::Timeout=180" remove $1
  fi
  if [[ "$PLATFORM" == "mac" ]]; then
    brew uninstall -q $1
  fi
  if [[ "$PLATFORM" == "arch" ]]; then
    sudo pacman -Rsc $1
  fi
  if [[ "$PACKAGEMANAGER" == "apk" ]]; then
    apk del $1
  fi
}

update_packages () {
  if [[ "$PLATFORM" == "ubuntu" ]]; then
    sudo apt-get -qq -o "DPkg::Lock::Timeout=180" update > /dev/null
  fi
  if [[ "$PLATFORM" == "raspbian" ]]; then
    sudo apt-get -qq -o "DPkg::Lock::Timeout=180" update > /dev/null
  fi
  if [[ "$PLATFORM" == "mac" ]]; then
    brew update -q
  fi
  if [[ "$PLATFORM" == "arch" ]]; then
    sudo pacman -Syu
    pacman -Rns $(pacman -Qdtq)	
  fi
  if [["$PACKAGEMANAGER" == "apk"]]; then
    apk update
  fi
}

upgrade_packages () {
  if [[ "$PLATFORM" == "ubuntu" ]]; then
    sudo -E apt-get -qq -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold" -o "DPkg::Lock::Timeout=180" upgrade > /dev/null
  fi
  if [[ "$PLATFORM" == "raspbian" ]]; then
    sudo -E apt-get -qq -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold" -o "DPkg::Lock::Timeout=180" upgrade > /dev/null
  fi
  if [[ "$PLATFORM" == "mac" ]]; then
    brew upgrade -q
  fi
  if [[ "$PLATFORM" == "arch" ]]; then
    sudo pacman -Syu
    pacman -Rns $(pacman -Qdtq)	
  fi
  if [["$PACKAGEMANAGER" == "apk"]]; then
    apk upgrade
  fi
}
