name = "fam"
author = "me"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a16f6066d771ba2814109eddf964ee4dc30700fc832e2d59c2d03cdd3fb52ba9"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
