name = "fam"
author = "me"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3056cdde629774742a375bcf29ff6e65c4ede4fb7a1c4a14f4926d4ceb504930"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
