name = "fam"
author = "me"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cd3aac03917df21da43b5ce5a9d96fd1993882cb9326acdf622c67323ec79552"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
