#!/usr/bin/env bash

source bw-dev-core

SESSION_PREFIX="✍️"
SESSION_NAME="web dev"
STARTER_COMMAND="cd $HOME/bitwarden/clients/apps/web; nvim"
WINDOW_NAME="dev"

ensure_command_installed nvim
start_window
