#!/usr/bin/env bash

source dev-core

SESSION_PREFIX="🛌"
SESSION_NAME="lazygit"
STARTER_COMMAND="lazygit"
WINDOW_NAME="."

ensure_command_installed tmux
ensure_command_installed lazygit
kill_session_if_exists
start_session
