#!/usr/bin/env bash

dev-scratchpad
dev-notes
dev-dotfiles

if [[ "$(hostname)" == "bw" || "$(hostname)" == "mac" ]]; then
  ssh-dev
else
  dev-lazygit
  dev-gh-dash
  bw-dev-binwarden
fi

start-tmux
