#!/usr/bin/env bash

source dev-core

SESSION_PREFIX="📡"
SESSION_NAME="ssh → dev"
STARTER_COMMAND="ssh dev -i ~/.ssh/$(hostname)"
WINDOW_NAME="connect"

ensure_command_installed tmux
kill_session_if_exists
start_session
