#!/usr/bin/env bash

source dev-core

SESSION_PREFIX="💾"
SESSION_NAME="htop"
STARTER_COMMAND="htop"
WINDOW_NAME="monitor"

ensure_command_installed tmux
ensure_command_installed htop
kill_session_if_exists
start_session
