#!/usr/bin/env bash

source dev-core

SESSION_PREFIX="💾"
SESSION_NAME="home"
WINDOW_NAME="."

function start_session () {
  log_info "Starting session \"$(full_session_name)\""
  tmux \
    new-session -d -s "$(full_session_name)" -n "${WINDOW_NAME}" -c '~' 'neofetch && tail -f /dev/null' \; \
    split-window -d -v -c '~' \; \
    split-window -d -h -c '~' 'htop' \; \
    split-window -h -t 2 -c '~' \; \
    send-keys -t 3 "${1}" \; \
    set-option -w remain-on-exit on > /dev/null 2>&1
}

function attach_to_session () {
  tmux a -t "$(full_session_name)"
}

ensure_command_installed tmux
tmux has-session -t "$(full_session_name)" > /dev/null 2>&1
if [ $? != 0 ]; then
  ensure_command_installed neofetch
  ensure_command_installed htop
  start_session
  attach_to_session
fi
