#!/usr/bin/env bash

source dev-core

SESSION_PREFIX="🚮"
SESSION_NAME="scratchpad"

if [ "$(tmux display-message -p -F "#{session_name}")" = "$(full_session_name)" ];then
    tmux detach-client
else
  tmux popup -d '#{pane_current_path}' -xC -yC -w95% -h95% -E "tmux attach -t \"$(full_session_name)\" || tmux new -s \"$(full_session_name)\""
fi
