#!/usr/bin/env bash

while [[ $# -gt 0 ]] 
do
  case $1 in
    d|dev )
      DEV="true"
      shift
      ;;

    n|nix )
      NIX="true"
      shift;;

    *)
      echo "Option ${1} is not supported by this command"
      shift
      ;;
  esac
done

if [ -n "$DEV" ] 
then
  $HOME/bin/windows/ssh-window ssh-dev
fi

if [ -n "$NIX" ] 
then
  $HOME/bin/windows/ssh-window ssh-nix
fi

