#!/usr/bin/env bash

source $DOTFILES_EX_DIR/installers/installers-core

install_neovim () {
  if [[ "$PACKAGEMANAGER" == "apt" ]]; then
    install_package build-essential
    install_package ripgrep
    install_package fd-find
    install_package gcc
    ln -s $(which fdfind) ~/bin/fd
    wget https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz
    tar xvzf nvim-linux64.tar.gz
    sudo rm -rf /usr/local/bin/nvim-linux64
    sudo mv -f nvim-linux64 /usr/local/bin
    cd /usr/local/bin/
    sudo ln -sf /usr/local/bin/nvim-linux64/bin/nvim nvim
    rm ~/nvim-linux64.tar.gz
    rm -rf ~/nvim-linux64
  fi

  if [[ "$PACKAGEMANAGER" == "brew" || "$PACKAGEMANAGER" == "pacman" || "PACKAGEMANAGER" == "apk" ]]; then
    install_package ripgrep
    install_package fd
    install_package gcc
    install_package neovim
  fi
}

install_neovim
