#!/usr/bin/env bash

source $DOTFILES_EX_DIR/installers/installers-core

install_neomutt () {
  if [[ "$PACKAGEMANAGER" == "apt" ]]; then
    install_package neomutt
  fi

  if [[ "$PACKAGEMANAGER" == "brew" ]]; then
    install_package neomutt
  fi
}

install_neomutt

