#!/usr/bin/env bash

source $DOTFILES_EX_DIR/installers/installers-core

install_fish () {
  if [[ "$PACKAGEMANAGER" == "apt" ]]; then
    sudo add-apt-repository ppa:fish-shell/release-3 -y
    update_packages
    install_package fish
  fi
  if [[ "$PACKAGEMANAGER" == "brew" || "$PACKAGEMANAGER" == "pacman" ]]; then
    install_package fish
  fi
}

install_omf () {
  NONINTERACTIVE=true fish -c "curl https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install | fish"
  fish -c "omf install foreign-env"
}

set_default_shell () {
  echo $(which fish) | sudo tee -a /etc/shells
  sudo chsh -s $(which fish) $(whoami)
}

install_fish
install_omf
set_default_shell

