#!/usr/bin/env bash

source $DOTFILES_EX_DIR/installers/installers-core

install_xserver () {
  install_package xorg-server
  install_package xorg-xauth 
  install_package xorg-xinit
  install_package xorg-xsetroot
  install_package xorg-xdpyinfo
  install_package xorg-xrandr
  install_package xorg-xrdb
  install_package xclip
  install_package xcb-util-xrm
}

install_xserver
