#!/usr/bin/bash

source $DOTFILES_EX_DIR/installers/installers-core

install_gh () {
  if [[ "$PACKAGEMANAGER" == "apt" ]]; then
    curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
    && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
    && update_packages \
    && install_package gh
  fi

  if [[ "$PACKAGEMANAGER" == "brew" ]]; then
    install_package gh
  fi

  if [[ "$PACKAGEMANAGER" == "pacman" ]]; then
    install_package github-cli
  fi
}

install_gh_dash () {
  gh extension install dlvhdr/gh-dash
  gh extension install github/gh-copilot
}

install_gh
install_gh_dash

