#!/usr/bin/env bash

source $DOTFILES_EX_DIR/installers/installers-core

install_bitwarden () {
  if ! command -v unzip
  then
    install_package unzip
  fi

  if [[ "$PACKAGEMANAGER" == "apt" || "$PACAKGEMANAGER" == "pacman" || "$PACKAGEMANAGER" == "apk" || "$PACKAGEMANAGER" == "dnf" ]]; then
    install_package unzip
    curl -s --location "https://vault.bitwarden.com/download/?app=cli&platform=linux" --output bw.zip
    unzip bw.zip -d . 
    chmod +x bw
    sudo mv bw /usr/local/bin
    rm bw.zip
  fi

  if [[ "$PACKAGEMANAGER" == "brew" ]]; then
    curl -s --location "https://vault.bitwarden.com/download/?app=cli&platform=macos" --output bw.zip
    unzip bw.zip -d . 
    chmod +x bw
    sudo mkdir -p /usr/local/bin
    sudo mv bw /usr/local/bin
    rm bw.zip
  fi
}

install_bitwarden

