#!/usr/bin/bash

source $DOTFILES_EX_DIR/installers/installers-core

install_mosh () {
  if [[ "$PACKAGEMANAGER" == "brew" ]]; then
    install_package mosh
  fi
  if [[ "$PACKAGEMANAGER" == "apt" ]]; then
    install_package mosh
  fi
}

install_mosh
