#!/usr/bin/env bash

source $DOTFILES_EX_DIR/installers/installers-core

install_starship () {
  if [[ "$PACKAGEMANAGER" == "apt" ]]; then
    sudo curl -sS https://starship.rs/install.sh | sudo sh
    touch ~/.config/starship-installed
  fi
  if [[ "$PACKAGEMANAGER" == "brew" ]]; then
    install_package starship
    touch ~/.config/starship-installed
  fi
  if [[ "$PACKAGEMANAGER" == "pacman" ]]; then
    install_package starship
    touch ~/.config/starship-installed
  fi
  if [[ "$PACKAGEMANAGER" == "apk" ]]; then
    install_package starship
    touch ~/.config/starship-installed
  fi
}

install_starship

