#!/usr/bin/env bash

source $DOTFILES_EX_DIR/installers/installers-core

install_no_machine () {
  if [[ "$PACKAGEMANAGER" == "brew" ]]; then
    brew install --cask nomachine
  fi
  if [[ "$PACKAGEMANAGER" == "pacman" ]]; then
    cd ~
    git clone https://aur.archlinux.org/nomachine.git
    cd nomachine
    sudo sed -i "s/_autoservice=n/_autoservice=y/g" ~/nomachine/PKGBUILD
    makepkg -sirc
    sudo pacman -Rns $(pacman -Qdtq)	
    sudo sed -i "s/su/system-remote-login/g" /etc/pam.d/nx
    sudo sed -i "/DefaultDesktopCommand/c\\\nDefaultDesktopCommand \"env DBUS_SESSION_BUS_ADDRESS=unix:path=\/run\/user\/$(id -u)\/bus ~\/bin\/os-management\/start-desktop-arch\"\n" /usr/NX/etc/node.cfg

    sudo systemctl enable --now nxserver.service
    sudo /etc/NX/nxserver --restart
  fi
}

install_no_machine
