#!/usr/bin/env bash

export BITWARDENCLI_APPDATA_DIR=~/.config/bw-p

login_to_bw () {
  bw logout
  BW_SESSION="$(bw login --raw)"
  bw sync
}

save_secrets () {
  bw get attachment .env --itemid ac755655-4d35-44bf-9bfc-b0ce013407c6 --session $BW_SESSION
  sudo mv .env $HOME
}

login_to_bw
save_secrets

